// <auto-generated />
using System;
using CashFlow.Consolidation.Worker.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CashFlow.Consolidation.Worker.Persistence.Migrations
{
    [DbContext(typeof(SaldoDiarioDbContext))]
    [Migration("20260824133246_AddLancamentosProcessados")]
    partial class AddLancamentosProcessados
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("consolidation")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CashFlow.Consolidation.Worker.Persistence.LancamentoProcessado", b =>
                {
                    b.Property<Guid>("LancamentoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ProcessadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LancamentoId");

                    b.ToTable("lancamentos_processados", "consolidation");
                });

            modelBuilder.Entity("CashFlow.Domain.Entidades.SaldoDiario", b =>
                {
                    b.Property<DateTime>("Data")
                        .HasColumnType("date");

                    b.Property<decimal>("TotalCreditos")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalDebitos")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Data");

                    b.ToTable("saldos_diarios", "consolidation");
                });
#pragma warning restore 612, 618
        }
    }
}
